### ISSUE TITLE
Add Proper Comments Where Needed

### ISSUE THREAD

**Issue by jackdp** [kachkaev/php-r#12]
When I was working on a solution to run php-r on Windows and I saw several files without comments and proper styling. When it is appropriate (likely after the Windows fix is merged), I want to add proper comments to necessary files.

**Comment by kachkaev** [comment]
Hi @jackdp,

What do you mean by ‘proper styling’? As far as I remember, the code of php-r follows [PSR-2](http://www.php-fig.org/psr/psr-2/) (but I can be possibly wrong).

Where exactly do you think the new comments would be useful? In my opinion, an ‘ideal code’ is one that has no comments at all as it can be understood without them. The only exception is PHPDOC for the API (```/** */```), which may be needed for auto-generating the documentation.

**Comment by jackdp** [comment]
@kachkaev, my apologizes for inconsistent word choice. I was only talking comments. The style is fine.

I believe any file that doesn't have summarize comments should have them. An example of summarize comments would be https://github.com/jackdp/University-Work/blob/master/Full%20Cybike%20Survey/src/Bikeshare/Bikeshare/Services/SpinText.php. Above each variable and function there are such comments. Though not always necessary, there have the potential of helping future individuals who work with the code. 

Since this is your code base, I will not push this further. I'll close this issue.
