### ISSUE TITLE
Rprocess->write takes too much time

### ISSUE THREAD

**Issue by jesusvazquez** [kachkaev/php-r#14]
Hi,

I'm trying to perform something with your repo. I found it really easy to use. Something weird is happening to me. 
I have this php class with a structure like this:

$r = new RCore(new CommandLineREngine('/usr/bin/R'));
$rProcess = $r->createInteractiveProcess();
$rProcess->start();
$rProcess->write(<<<EOF
//////// BIG SCRIPT
EOF
    );

$rProcess->write(<<<EOF
///////// GET SOME VARIABLE VALUE
EOF
    );

$result = $rProcess->getLastWriteOutput();
$rProcess->stop();
return $result;

If I execute this once it rans in 24 seconds but if i reload the page if takes infinity. I updated my webserver timeout to 1 minut and I just get a timeout...

I don't understand why this is happening. The script rans in 1 second in Rstudio and it takes too much with php and this repo... what am i missing? Is this a repo problem? or is it my fault?

Best Regards.

**Comment by kachkaev** [comment]
Hi @jesusvazquez,

What operating system are you running the script in? What is the code version? There used to be a bug similar to what you are describing, but it must have been resolved 20 days ago (see #13).

**Comment by jesusvazquez** [comment]
Hi @kachkaev 

It's running under the Laravel's vagrant box called Homestead http://laravel.com/docs/4.2/homestead  which is an Ubuntu 64 bit machine.

R is 3.1.1
php-r composer dependency is "kachkaev/php-r": "1.0.*@dev" and it says it's updated.
PHP is 5.6.6

**Comment by kachkaev** [comment]
This problem can be related to some issues with the pipes, through which the data comes from R to PHP. Unfortunately it won't be possible for to me to see your bug in action, but I can suggest looking at these lines: 541f68a9b60c99eeb2f95ca511ab6ca67f18116e. If you try debugging what's in $out, this might be a clue to a solution with hanging. It is possible that one of the while loops keeps looping because $out/$currentCommandOutput contains chunks of stop sequences rather than them in full.

**Comment by jesusvazquez** [comment]
Right now I'm kinda bussy. I solved it manually using exec(), opening an R process and reading the output. 

I would like to do it with your library so when I have more time I'll try to check it out.

Best Regards.

**Comment by tallsam** [comment]
I just hit this issue as the R script was outputting data using cat(). All working now though. Cheers.

**Comment by kachkaev** [comment]
Hey guys,

Looks like @Cedroux has brought a solution for this long-standing issue – see #35. Could you please try it and share your experience below?
