### ISSUE TITLE
$rOutputParser->numericVector does not work for Quantile return from R

### ISSUE THREAD

**Issue by gb5256** [kachkaev/php-r#16]
If I try this:
$rProcess->write('quantile(data, c(0.25, 0.5, 0.75), type = 6)');
and then do a 
$rOutputParser->numericVector
The output will cut off the first number of the 0.25 quantile result.
The problem might lay in the fact, that the output from R has a linebreak inside.

gb5256

**Comment by kachkaev** [comment]
I acknowledge that there might be problems with the parser as I haven't tested it much. Thank you @gb5256 for spotting this one in particular. Could you please trying to patch the code and submit a PR? I'll merge it if it does not break existing stuff.

**Comment by gb5256** [comment]
I can help you where the problem is.
The below output shows some return from R. In the middle section is the Quantile output.

[1] 220
[1] 169
  25%   50%   75% 
147.5 160.0 195.0 
[1] 13.45362
[1] 30.08322
[1] 51

As you see, it does not start with the [1]. But your parser looks for the bracket.
Line 45 of your parser says:
 $numbersAsStr = substr($row, strpos($row, ']') + 1);
As the position of the ] is zero, it adds 1 to it and that way removes the leading 1 from the string 147.5
So you need something like this
    If (strpos($row, ']') != false) {
       $numbersAsStr = substr($row, strpos($row, ']') + 1); //this is as it was
    } else {
       $numbersAsStr = $row; //for the case that there is no bracket, it will return the whole row as string
    }

**Comment by kachkaev** [comment]
Cool, cheers!
