### ISSUE TITLE
Path to R

### ISSUE THREAD

**Issue by demoreno** [kachkaev/php-r#17]
Good afternoon, alexander, greetings from Venezuela, first of all thank you for providing this solution Connection to R, I'm trying to implement this solution to a personal project, but I have an issue with the way R, I am working on windows and I should not placed exactly try to invoke the .exe in the root folder R without positive results. Could you tell me to be placed in that parameter?

Thank You

PS: Sorry for my English, in my country it is not our primary language

**Comment by kachkaev** [comment]
Hi @demoreno,

I haven't tried the library on Windows myself, but there is a discussion of possible issues in another thread: #7. Have a look and let others know if you manage to make things working.
