### ISSUE TITLE
Exchanging data from array

### ISSUE THREAD

**Issue by collmomo** [kachkaev/php-r#20]
Let's say you have an array with around 1 million row, is there an easy way to load that in R using your library or do I have to write to a csv, then write a R script and tell it to open that .csv.

**Comment by kachkaev** [comment]
Hi @collmomo! Yes, I would do it this way, using CSV file. Using PHPR is similar to talking to R via the console. It is unlikely that someone would want to copy and paste 1 million rows as a single string and then feed R that way.

When you generate a CSV file in PHP, you often can do this line-by-line. This will require less memory and will thus make the script more robust.

**Comment by kachkaev** [comment]
Please close this issue if you are satisfied with the answer :–)
