### ISSUE TITLE
 PHP Fatal error:  Class 'Kachkaev\\PHPR\\RCore' not found in /var/www/html/R_lib/index.php on line 5

### ISSUE THREAD

**Issue by AsrRajiv** [kachkaev/php-r#21]
Hi,

I have downloaded the zip file and extracted.When i run the file it showing 500 Internal server error. I have followed some of the tweaks that we should use autoload.php. I am not clear. Can any help me?

**Comment by kachkaev** [comment]
Hi @AsrRajiv,

Can you try installing the library using composer? This is the standard way to add libraries to your code. You won't need to tweak autoload.php yourself then.

**Comment by kachkaev** [comment]
For someone who is facing something similar, please see https://github.com/kachkaev/php-r/issues/22
