### ISSUE TITLE
PHP Fatal error:  Class 'src\\Kachkaev\\PHPR\\RCore' not found

### ISSUE THREAD

**Issue by AsrRajiv** [kachkaev/php-r#22]
Hi,

As you have said i have downloaded composer.phar file and saved in my path and installed the compose.phar using "php composer.phar install --no-dev".It's installed and i have got vendor folder. Inside vendor folder i can now able to find "autoload.php". But it's not working.still i am facing **500 Internal Server Error** i have copied the composer folder and autoload.php from vendor folder and pasted in my root folder and tried to run. but no improvements. can u help me?

Here is my index.php  file :
-----------------------------------------
<?php
use \src\Kachkaev\PHPR\RCore;
use \src\Kachkaev\PHPR\Engine\CommandLineREngine;

include 'autoload.php';

$r = new RCore(new CommandLineREngine('/usr/bin/R'));
$result = $r->run('1 + 1');
echo $result;

**Comment by kachkaev** [comment]
Can you try replacing use \src\Kachkaev\... with use Kachkaev\...?

**Comment by AsrRajiv** [comment]
Hi,

Thankyou!!!
We have connected the library. I want to know how to pass php array to R . I used serialize in php to convert to string. but i am not sure R is receiving. Can u help me how to  receive an array in R from php.

**Comment by kachkaev** [comment]
The library lets you to exchange text with R just as you are doing in a command line. If you would like to pass an array, you'll first need to convert it from a PHP array to some string that can be understood by R. The same is for the data that is being received from R to PHP - it's just a text.

There are a couple of functions in [ROutputParser.php](https://github.com/kachkaev/php-r/blob/master/src/Kachkaev/PHPR/ROutputParser.php) that help you with turning the received text to PHP variables, but that list is very short. Feel free to add new variable dumpers and parsers  and contribute them back to the library!

Also feel free to close this issue if you think that it has been fixed.
