### ISSUE TITLE
Not working in php7

### ISSUE THREAD

**Issue by giriannamalai** [kachkaev/php-r#23]
I cloned and tried to run. but it's saying, It only support php 5.3 . what can i do

**Comment by kachkaev** [comment]
Hi @giriannamalai, thanks for reporting the issue. Can you try editing `composer.json` by replacing `"php": "~5.3"` with `"php": ">=5.3"`? If it works in PHP 7 afterwards, I'll update this dependency on master.

If your issue is not related to `composer.json`, what error are you seeing?

**Comment by kachkaev** [comment]
I believe that this was closed by #24. Let's reopen this issue again if something is still not working in PHP 7.

**Comment by garak** [comment]
I can confirm that php7 is working now
