### ISSUE TITLE
rCore not found after composer update

### ISSUE THREAD

**Issue by gb5256** [kachkaev/php-r#25]
Hi,
I have run a composer update and now (without changing anything else) I get this error:
Class 'Kachkaev\PHPR\RCore' not found

It did work before normal, what has changed?

gb5256

**Comment by kachkaev** [comment]
Can it be related to how your composer's autoloader is working? I also had this pretty pity error in Symfony projects and it turned out that php's autoload in vendor was not generating correctly. It may be relevant to "autoload" section in package.json.

If you find a solution, could you please share what has happened?

**Comment by gb5256** [comment]
autoload_psr4 shows this:

     'Kachkaev\\PHPR\\' => array($vendorDir . '/kachkaev/php-r/src'),

but should show this:

     'Kachkaev\\PHPR\\' => array($vendorDir . '/kachkaev/php-r/src/Kachkaev/PHPR'),

The composer takes this info from you composer.json:

       "autoload": {
        "psr-4": {
            "Kachkaev\\PHPR\\": "src"
        }
    },


My knowledge about composer is not good enough to proceed. Is this something you need to change or is this my local problem?

thanks again,
gb5256

**Comment by kachkaev** [comment]
Not sure why this happens, unfortunately. I'm not a big expert in PHP's autoloading, it often confuses me too. In any case, I suppose that this is some general problem related to how things are configured in your composer file. Wish you luck!

**Comment by kachkaev** [comment]
Hi @gb5256, there're probably good news to share – #27 must have fixed your bug, thanks to @ghola! Let know if you still experience issues – this might help others who use php-r in their work!
