### ISSUE TITLE
Large strings cause IncompleteRCommandException

### ISSUE THREAD

**Issue by andyG8** [kachkaev/php-r#28]
I am passing JSON data from PHP to R as

`$rProcess->write("t1<-fromJSON('$ser_j', simplifyVector = TRUE, simplifyDataFrame=TRUE)");`

It works fine on relatively short strings $ser_j (tested up to 130-150 3-digit numbers in a string). But for larger strings, it returns an error:

> Warning: include(Kachkaev/PHPR/Process/IncompleteRCommandException.php): failed to open stream: No such file or directory in ...

It looks as large strings are truncated and the R command line becomes incomplete.
My questions:
1. Is there any limit on the size of strings/data being passed to R?
2. If yes, how would you suggest to pass large data sets? Via MySQL?
3. How to fix the error of missing IncompleteRCommandException.php? I am using the following namespaces (classes are loaded via **spl_autoload_register**):

```
use Kachkaev\PHPR\RCore;
use RKachkaevPHPR\Engine\CommandLineREngine;
use Kachkaev\PHPR\Exception; 
``` 
Thanks!

**Comment by kachkaev** [comment]
Hi @andyG8!

Thanks for reporting all this. Will try to answer:

1. I believe that yes, there is a limit in how much you can pass to php-r directly. The library is just a thin command line wrapper, so I believe the limit depends on your CLI.

2. MySQL can be an option, yes. What you can also try is just to ask R to open a specific file by its path. If the R interpreter is on the same machine (which is always the case with `CommandLineREngine`), both PHP and R have access to the same filesystem.  You can just save your file as JSON and tell R where it is.

3. Great catch! Looks like `IncompleteRCommandException` was not referenced correctly. Can you try pulling and checking if the fix worked?

**Comment by andyG8** [comment]
Hi Alexander,

Thank you, the IncompleteCommandException has been fixed. I am using the MySQL option to pass large data sets and it works perfectly fine.

Cheers,
Andy
