### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tuupola** [kachkaev/php-r#31]
Could you tag a release, for example `0.1.0`.  I would like to use this package as part of a library I am developing. Cannot use `dev-master` because it is not guaranteed to brake.

**Comment by kachkaev** [comment]
Thanks for your suggestion @tuupola! I've tagged the latest commit on master as `v1.0.0` (the library has been more or less stable for a while). Let know if anything has not worked for you – we’ll have a look!
