### ISSUE TITLE
There is no extension able to load the configuration for "kachkaev_php_r" (in C:\wamp\www\dashboard_cgi\app/config\config.yml). Looked for namespace "kachkaev_php_r", found , "kachkaev_phpr", 

### ISSUE THREAD

**Issue by fati777** [kachkaev/php-r#32]
Im triying to install this bundle, it seems very interesting but I failed , can you help me please to solve this issue: ->"There is no extension able to load the configuration for "kachkaev_php_r" (in C:\wamp\www\dashboard_cgi\app/config\config.yml). Looked for namespace "kachkaev_php_r", found , "kachkaev_phpr""
 Im working with symfony 3 and this is my services.yml:
`services:
     kachkaev_php_r.core:
         class: Kachkaev\PHPR\RCore
         arguments: ['@kachkaev_php_r.engine.command_line']
 
     kachkaev_php_r.engine.command_line:
          class: Kachkaev\PHPR\Engine\CommandLineREngine
          arguments: ['%kachkaev_php_r.engine.command_line.path_to_r%']`
and my config.yml
kachkaev_php_r:
    default_enginge: 'command_line'    # default R engine (command_line is the only one currently implemented)  
    engines:
        command_line:
            path_to_r: '%kernel.root_dir%/../R'    # path to R interpreter
when I try just with kachkaev_phpr i get this error
Unrecognized options "default_enginge, engines" under "kachkaev_php_r"
So I don't khow how to configure this bundle

**Comment by kachkaev** [comment]
Hi @fati777 

Have you been trying this packaged or [KachkaevPHPRBundle](https://github.com/kachkaev/KachkaevPHPRBundle) instead? I'd recommend the latter, because its a proper Symfony bundle sitting on top of php-r.

Let know how things are after you try the bundle!

**Comment by fati777** [comment]
hi @Alexander Kachkev
do you know? , I realy need this bridge to do the forecast with R .and I
realy appreciate your work I have been try the package that you recommend
https://github.com/kachkaev/KachkaevPHPRBundle. But it is not working


2017-05-29 11:59 GMT+01:00 Alexander Kachkaev <notifications@github.com>:

**Comment by kachkaev** [comment]
Could you please share some details of the error you are facing?

**Comment by fati777** [comment]
ok , with great pleasure, I will give you more details
first I m working with symfony 3 , and to dowload your library , I edit my composer.json with:
"kachkaev/php-r-bundle": "dev-master", then I execute the command:
$ php composer.phar update kachkaev/php-r-bundlle, my cofiguration is(config.yml):
kachkaev_php_r:
    default_enginge: command_line    # default R engine (command_line is the only one currently implemented)  
    engines:
        command_line:
            path_to_r: '%kernel.root_dir%/../R/R-3.4.0/bin/R.exe'   # path to R interpreter

the error that I get is :(i did not use the librairie yet):
Whoops, looks like something went wrong.


FileLoaderLoadException in FileLoader.php line 118:

There is no extension able to load the configuration for "kachkaev_php_r" (in C:\wamp\www\dashboard_cgi\app/config\config.yml). Looked for namespace "kachkaev_php_r", found "framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "admin_admin", "admin_user", "fos_user", "ob_highcharts", "cgi_coordinateur", "manager_manager", "waldo_datatable", "fos_js_routing", "cgi_graphe", "liuggio_excel", "manipulation_excel", "full_calendar", "kachkaev_phpr", "debug", "web_profiler", "sensio_distribution" in C:\wamp\www\dashboard_cgi\app/config\config.yml (which is being imported from "C:\wamp\www\dashboard_cgi\app/config/config_dev.yml").
in FileLoader.php line 118
2.at FileLoader->import('config.yml', null, false, 'C:\\wamp\\www\\dashboard_cgi\\app/config/config_dev.yml') in YamlFileLoader.php line 130
3.at YamlFileLoader->parseImports(array('imports' => array(array('resource' => 'config.yml')), 'framework' => array('router' => array('resource' => '%kernel.root_dir%/config/routing_dev.yml', 'strict_requirements' => true), 'profiler' => array('only_exceptions' => false)), 'web_profiler' => array('toolbar' => true, 'intercept_redirects' => false), 'monolog' => array('handlers' => array('main' => array('type' => 'stream', 'path' => '%kernel.logs_dir%/%kernel.environment%.log', 'level' => 'debug', 'channels' => array('!event')), 'console' => array('type' => 'console', 'channels' => array('!event', '!doctrine'))))), 'C:\\wamp\\www\\dashboard_cgi\\app/config/config_dev.yml') in YamlFileLoader.php line 79
4.at YamlFileLoader->load('C:\\wamp\\www\\dashboard_cgi\\app/config/config_dev.yml', null) in DelegatingLoader.php line 45
5.at DelegatingLoader->load('C:\\wamp\\www\\dashboard_cgi\\app/config/config_dev.yml') in AppKernel.php line 61
6.at AppKernel->registerContainerConfiguration(object(DelegatingLoader)) in Kernel.php line 581
7.at Kernel->buildContainer() in Kernel.php line 486
8.at Kernel->initializeContainer() in Kernel.php line 116
9.at Kernel->boot() in Kernel.php line 165
10.at Kernel->handle(object(Request)) in app_dev.php line 28

**Comment by kachkaev** [comment]
@fati777 could you please reinstall `kachkaev/php-r-bundle` at `v2.1` and try again? Should be fixed now. Two things to keep in mind:
*   `kachkaev_php_r`renamed to `kachkaev_phpr`
*   there was a typo in readme for `default_engine` (I incorrectly spelled it as `default_enginge`)

Let me know if the config is still invalid, I'll reopen this issue. New issues related to the Symfony bundle can go directly to its repo https://github.com/kachkaev/KachkaevPHPRBundle
