### ISSUE TITLE
is there a way to execute R script in the php file

### ISSUE THREAD

**Issue by msheranga** [kachkaev/php-r#36]
I am trying to find the way connect R and php file. but i was unable. i used php exec() function also but it is not gives the output please help

**Comment by kachkaev** [comment]
Hi @msheranga! Could you please share the code you are trying to run or generate a small similar example?

**Comment by msheranga** [comment]
thanks. 
#test1.R
print("R programming")

#php file 

<?php 
$a=exec("Rscript C:/wamp64/www/test/test1.R"); 
var_dump($a);
?>
but there is no output

**Comment by kachkaev** [comment]
@msheranga please have a look at the examples in [this repo's README.md](https://github.com/kachkaev/php-r) on how to use `php-r`. I don't see any mentioning of ` Kachkaev\PHPR\...` in your example, which means that you are not using the library. If you have any issue with [`php-r`](https://github.com/kachkaev/php-r) (not just combining PHP and R), feel free to further comment on this issue.
