### ISSUE TITLE
R script that expects parameters

### ISSUE THREAD

**Issue by Kamakazi152** [kachkaev/php-r#43]
I am having some trouble finding the syntax on how to call an R script and pass it the parameter it is expecting from a PHP function. I basically have a script that is expecting a json object and I am not sure how to call it and send it that object in order to get the data back.

**Comment by kachkaev** [comment]
Hi Kamakazi152, I'm sorry but I don't maintain the project any more. If your tech stack is not frozen, feel free to reconsider the building blocks in your project. This link may be a good place to find your way around:
https://github.com/kamranahmedse/developer-roadmap/
