### ISSUE TITLE
class RCore not found 

### ISSUE THREAD

**Issue by EstherGon** [kachkaev/php-r#6]
use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine;
$r = new RCore(new CommandLineREngine('/usr/bin/R'));

$result = $r->run(<<<EOF

e<-0.4
p<-0.3
pse<-0.2

e+p

EOF
    );

echo $result;

when I use this Rcode or other Rcode appear class RCore($r = new RCore(new CommandLineREngine('/usr/bin/R'));)  not found , what happen ? tnx !

**Comment by kachkaev** [comment]
Hi @EstherGon,

Please make sure that PHPR classes have been loaded. If you are not using a framework that does this for you, you should link to all PHPR php filess manually. See http://php.net/manual/en/language.oop5.autoload.php for more details.
