### ISSUE TITLE
Fatal error: Class 'Kachkaev\PHPR\RCore' not found 

### ISSUE THREAD

**Issue by tejra** [kachkaev/php-r#9]
I am using php-r package to use R script from php but it is showing error.
Fatal error: Class 'Kachkaev\PHPR\RCore' not found 

<?php
use Kachkaev\PHPR\RCore;
use Kachkaev\PHPR\Engine\CommandLineREngine; 

//showing error here
$r = new RCore(new CommandLineREngine('/usr/bin/R'));

$result = $r->run(<<<EOF
x = 1
y = 2
x + y
x + z
x - y
EOF
    );

echo $result;
?>

**Comment by kachkaev** [comment]
Hi @tejra,

Please see issue #6 for what to do. Hope it helps.
